version: '3'
services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "6666:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - frontend
      - backend
    depends_on:
      - php

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - backend

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "6001:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1
    networks:
      - backend


networks:
  frontend:
  backend:

volumes:
  db_data: {}
